site_name: MkLorum
nav:
  - Home: index.md
  - About: about.md
# theme: readthedocs
# theme:
#     name: simple-blog
markdown_extensions:
  - admonition
  - attr_list
  - md_in_html
  - pymdownx.blocks.caption
extra_css:
  - assets/stylesheets/extra.css
